---
- name: restart mysql
  become: true
  service:
          name: mysql
          state: restarted

- name: start mysqld
  service:
          name: mysqld
          state: started
          enabled: true

- name: restart mysqld
  become: true
  service:
          name: mysqld
          state: restarted
