---
- name: Install MySQL repo
  yum:
         name: http://repo.mysql.com/mysql57-community-release-el7-10.noarch.rpm
         state: present
- name: Import GPG
  shell: rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2022

- name: Install MySql DB
  yum:
          name: "{{ item }}"
          state: present
  with_items:
          - mysql-server
          - MySQL-python
  notify: start mysqld

- name: update Mysql root pass for all root acc
  mysql_user:
          login_host: 'localhost'
          login_user: 'root'
          login_password: 'P@ssword001'
          name: root
          password: "{{ mysql_root_pass }}"
          state: present

- name: Copy the root credentials as my.cnf file
  template:
          src: root.cnf.j2
          dest: ~/.my.cnf
          mode: 0600

- name: Ensure anonymous user are not in the database
  mysql_user:
          name: ''
          host: "{{ item }}"
          state: absent
  with_items:
          - localhost
          - "{{ ansible_hostname }}"

- name: Remove the test database
  mysql_db:
          name: test
          state: absent
  notify:
          - restart mysqld
