---
- name: Install MySQL
  yum:
         name: http://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm
         state: present
- name: Install Mysql
  become: true
  yum:
          name: "{{ item }}"
          state: present
          update_cache: yes
  with_items:
          - MySQL-python
          - mysql-server
- name: update Mysql root pass for all root acc
  mysql_user:
          name: root
          host: "{{ item }}"
          password: "{{ mysql_root_pass }}"
          state: present
  with_items:
          - "{{ ansible_hostname }}"
          - 172.0.0.1
          - ::1
          - localhost
- name: Copy the root credentials as my.cnf file
  template:
          src: root.cnf.j2
          dest: ~/.my.cnf
          mode: 0600
- name: Ensure anonymous user are not in the database
  mysql_user:
          name: ''
          host: "{{ item }}"
          state: absent
  with_items:
          - localhost
          - "{{ ansible_hostname }}"
- name: Remove the test database
  mysql_db:
          name: test
          state: absent
  notify:
          - restart mysql
